# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='kokaze',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\x12\x06kokaze\"\x18\n\x08\x46ilename\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x0eTestCaseNumber\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1c\n\x0cTestCaseName\x12\x0c\n\x04name\x18\x01 \x01(\t\"1\n\x0fTestCaseContent\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x03(\t\"2\n\x0f\x43ppCheckContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t2\x82\x01\n\rpluginService\x12\x37\n\x08\x63ppCheck\x12\x10.kokaze.Filename\x1a\x17.kokaze.CppCheckContent\"\x00\x12\x38\n\thighLight\x12\x10.kokaze.Filename\x1a\x17.kokaze.TestCaseContent\"\x00\x62\x06proto3'
)




_FILENAME = _descriptor.Descriptor(
  name='Filename',
  full_name='kokaze.Filename',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='kokaze.Filename.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=46,
)


_TESTCASENUMBER = _descriptor.Descriptor(
  name='TestCaseNumber',
  full_name='kokaze.TestCaseNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='kokaze.TestCaseNumber.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=80,
)


_TESTCASENAME = _descriptor.Descriptor(
  name='TestCaseName',
  full_name='kokaze.TestCaseName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='kokaze.TestCaseName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=110,
)


_TESTCASECONTENT = _descriptor.Descriptor(
  name='TestCaseContent',
  full_name='kokaze.TestCaseContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='kokaze.TestCaseContent.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='kokaze.TestCaseContent.content', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=161,
)


_CPPCHECKCONTENT = _descriptor.Descriptor(
  name='CppCheckContent',
  full_name='kokaze.CppCheckContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='kokaze.CppCheckContent.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='kokaze.CppCheckContent.output', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['Filename'] = _FILENAME
DESCRIPTOR.message_types_by_name['TestCaseNumber'] = _TESTCASENUMBER
DESCRIPTOR.message_types_by_name['TestCaseName'] = _TESTCASENAME
DESCRIPTOR.message_types_by_name['TestCaseContent'] = _TESTCASECONTENT
DESCRIPTOR.message_types_by_name['CppCheckContent'] = _CPPCHECKCONTENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Filename = _reflection.GeneratedProtocolMessageType('Filename', (_message.Message,), {
  'DESCRIPTOR' : _FILENAME,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:kokaze.Filename)
  })
_sym_db.RegisterMessage(Filename)

TestCaseNumber = _reflection.GeneratedProtocolMessageType('TestCaseNumber', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASENUMBER,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:kokaze.TestCaseNumber)
  })
_sym_db.RegisterMessage(TestCaseNumber)

TestCaseName = _reflection.GeneratedProtocolMessageType('TestCaseName', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASENAME,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:kokaze.TestCaseName)
  })
_sym_db.RegisterMessage(TestCaseName)

TestCaseContent = _reflection.GeneratedProtocolMessageType('TestCaseContent', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASECONTENT,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:kokaze.TestCaseContent)
  })
_sym_db.RegisterMessage(TestCaseContent)

CppCheckContent = _reflection.GeneratedProtocolMessageType('CppCheckContent', (_message.Message,), {
  'DESCRIPTOR' : _CPPCHECKCONTENT,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:kokaze.CppCheckContent)
  })
_sym_db.RegisterMessage(CppCheckContent)



_PLUGINSERVICE = _descriptor.ServiceDescriptor(
  name='pluginService',
  full_name='kokaze.pluginService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=216,
  serialized_end=346,
  methods=[
  _descriptor.MethodDescriptor(
    name='cppCheck',
    full_name='kokaze.pluginService.cppCheck',
    index=0,
    containing_service=None,
    input_type=_FILENAME,
    output_type=_CPPCHECKCONTENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='highLight',
    full_name='kokaze.pluginService.highLight',
    index=1,
    containing_service=None,
    input_type=_FILENAME,
    output_type=_TESTCASECONTENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLUGINSERVICE)

DESCRIPTOR.services_by_name['pluginService'] = _PLUGINSERVICE

# @@protoc_insertion_point(module_scope)
