# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class pluginServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cppCheck = channel.unary_unary(
                '/kokaze.pluginService/cppCheck',
                request_serializer=test__pb2.Filename.SerializeToString,
                response_deserializer=test__pb2.CppCheckContent.FromString,
                )
        self.highLight = channel.unary_unary(
                '/kokaze.pluginService/highLight',
                request_serializer=test__pb2.Filename.SerializeToString,
                response_deserializer=test__pb2.TestCaseContent.FromString,
                )


class pluginServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cppCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def highLight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_pluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'cppCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.cppCheck,
                    request_deserializer=test__pb2.Filename.FromString,
                    response_serializer=test__pb2.CppCheckContent.SerializeToString,
            ),
            'highLight': grpc.unary_unary_rpc_method_handler(
                    servicer.highLight,
                    request_deserializer=test__pb2.Filename.FromString,
                    response_serializer=test__pb2.TestCaseContent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kokaze.pluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class pluginService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cppCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kokaze.pluginService/cppCheck',
            test__pb2.Filename.SerializeToString,
            test__pb2.CppCheckContent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def highLight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kokaze.pluginService/highLight',
            test__pb2.Filename.SerializeToString,
            test__pb2.TestCaseContent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
