# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import testgen_pb2 as testgen__pb2


class TestCaseGenerationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.kleeGeneration = channel.unary_unary(
                '/testgen.TestCaseGeneration/kleeGeneration',
                request_serializer=testgen__pb2.FileName.SerializeToString,
                response_deserializer=testgen__pb2.TestCaseNumber.FromString,
                )
        self.kleeShow = channel.unary_unary(
                '/testgen.TestCaseGeneration/kleeShow',
                request_serializer=testgen__pb2.TestCaseName.SerializeToString,
                response_deserializer=testgen__pb2.TestCaseContent.FromString,
                )


class TestCaseGenerationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def kleeGeneration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def kleeShow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestCaseGenerationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'kleeGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.kleeGeneration,
                    request_deserializer=testgen__pb2.FileName.FromString,
                    response_serializer=testgen__pb2.TestCaseNumber.SerializeToString,
            ),
            'kleeShow': grpc.unary_unary_rpc_method_handler(
                    servicer.kleeShow,
                    request_deserializer=testgen__pb2.TestCaseName.FromString,
                    response_serializer=testgen__pb2.TestCaseContent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testgen.TestCaseGeneration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestCaseGeneration(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def kleeGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testgen.TestCaseGeneration/kleeGeneration',
            testgen__pb2.FileName.SerializeToString,
            testgen__pb2.TestCaseNumber.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def kleeShow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testgen.TestCaseGeneration/kleeShow',
            testgen__pb2.TestCaseName.SerializeToString,
            testgen__pb2.TestCaseContent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
