# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testgen.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtestgen.proto\x12\x07testgen\"\x18\n\x08\x46ileName\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x0eTestCaseNumber\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1c\n\x0cTestCaseName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fTestCaseContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2\x93\x01\n\x12TestCaseGeneration\x12>\n\x0ekleeGeneration\x12\x11.testgen.FileName\x1a\x17.testgen.TestCaseNumber\"\x00\x12=\n\x08kleeShow\x12\x15.testgen.TestCaseName\x1a\x18.testgen.TestCaseContent\"\x00\x62\x06proto3')



_FILENAME = DESCRIPTOR.message_types_by_name['FileName']
_TESTCASENUMBER = DESCRIPTOR.message_types_by_name['TestCaseNumber']
_TESTCASENAME = DESCRIPTOR.message_types_by_name['TestCaseName']
_TESTCASECONTENT = DESCRIPTOR.message_types_by_name['TestCaseContent']
FileName = _reflection.GeneratedProtocolMessageType('FileName', (_message.Message,), {
  'DESCRIPTOR' : _FILENAME,
  '__module__' : 'testgen_pb2'
  # @@protoc_insertion_point(class_scope:testgen.FileName)
  })
_sym_db.RegisterMessage(FileName)

TestCaseNumber = _reflection.GeneratedProtocolMessageType('TestCaseNumber', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASENUMBER,
  '__module__' : 'testgen_pb2'
  # @@protoc_insertion_point(class_scope:testgen.TestCaseNumber)
  })
_sym_db.RegisterMessage(TestCaseNumber)

TestCaseName = _reflection.GeneratedProtocolMessageType('TestCaseName', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASENAME,
  '__module__' : 'testgen_pb2'
  # @@protoc_insertion_point(class_scope:testgen.TestCaseName)
  })
_sym_db.RegisterMessage(TestCaseName)

TestCaseContent = _reflection.GeneratedProtocolMessageType('TestCaseContent', (_message.Message,), {
  'DESCRIPTOR' : _TESTCASECONTENT,
  '__module__' : 'testgen_pb2'
  # @@protoc_insertion_point(class_scope:testgen.TestCaseContent)
  })
_sym_db.RegisterMessage(TestCaseContent)

_TESTCASEGENERATION = DESCRIPTOR.services_by_name['TestCaseGeneration']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILENAME._serialized_start=26
  _FILENAME._serialized_end=50
  _TESTCASENUMBER._serialized_start=52
  _TESTCASENUMBER._serialized_end=84
  _TESTCASENAME._serialized_start=86
  _TESTCASENAME._serialized_end=114
  _TESTCASECONTENT._serialized_start=116
  _TESTCASECONTENT._serialized_end=150
  _TESTCASEGENERATION._serialized_start=153
  _TESTCASEGENERATION._serialized_end=300
# @@protoc_insertion_point(module_scope)
